import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  assertFails,
  assertSucceeds,
  initializeTestEnvironment,
} from '@firebase/rules-unit-testing';
import {
  collection,
  doc,
  getDoc,
  getDocs,
  setDoc,
  updateDoc,
  deleteDoc,
  deleteField,
  Timestamp,
} from 'firebase/firestore';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '../..');

const testEnv = await initializeTestEnvironment({
  projectId: 'herbaformix-rules-test',
  firestore: {
    rules: fs.readFileSync(path.join(projectRoot, 'firestore.rules'), 'utf8'),
  },
});

const consultantUid = 'consultant-uid';
const otherConsultantUid = 'other-consultant-uid';
const customerDocId = 'customer-doc-id';
const linkedCustomerUid = 'linked-customer-uid';
const unlinkedCustomerUid = 'unlinked-customer-uid';

function authDb(uid) {
  return testEnv.authenticatedContext(uid).firestore();
}

function unauthDb() {
  return testEnv.unauthenticatedContext().firestore();
}

function scheduledFollowUp(overrides = {}) {
  return {
    consultantId: consultantUid,
    customerId: customerDocId,
    customerFirstName: 'Ayse',
    customerLastName: 'Yilmaz',
    dueDate: Timestamp.fromDate(new Date('2026-07-20T09:00:00Z')),
    title: '3. Gun Kontrolu',
    isCompleted: false,
    notes: 'Kisa not',
    createdAt: Timestamp.fromDate(new Date('2026-07-11T09:00:00Z')),
    isAutoGenerated: false,
    ...overrides,
  };
}

function recipeDocument(overrides = {}) {
  return {
    productId: 'formul1_id',
    title: 'Distribütör Shake',
    description: 'Test için yayınlanan shake tarifi.',
    imageUrl: null,
    videoUrl: null,
    prepTimeMin: 5,
    calories: 200,
    goals: ['healthy_living'],
    tags: ['shake'],
    ingredients: [{ name: 'Formül 1', amount: '2 ölçek', note: null }],
    steps: ['Malzemeleri karıştırın.'],
    nutritionInfo: null,
    tips: null,
    isRecommended: false,
    ...overrides,
  };
}

function orderDocument(overrides = {}) {
  return {
    userId: consultantUid,
    customerId: linkedCustomerUid,
    customerName: 'Customer',
    items: [{ productId: 'formula-1', productName: 'Formula 1', quantity: 1 }],
    orderDate: Timestamp.fromDate(new Date('2026-07-16T09:00:00Z')),
    status: 'OrderStatus.pending',
    totalAmount: 500,
    totalVpEarned: 10,
    notes: '',
    shippingAddress: '',
    ...overrides,
  };
}

async function seedBaseData() {
  await testEnv.withSecurityRulesDisabled(async (context) => {
    const db = context.firestore();
    await setDoc(doc(db, 'userProfiles', consultantUid), {
      email: 'consultant@example.com',
      role: 'distributor',
      name: 'Consultant',
    });
    await setDoc(doc(db, 'userProfiles', otherConsultantUid), {
      email: 'other@example.com',
      role: 'distributor',
      name: 'Other',
    });
    await setDoc(doc(db, 'userProfiles', linkedCustomerUid), {
      email: 'customer@example.com',
      role: 'customer',
      name: 'Customer',
      assignedDistributorId: consultantUid,
    });
    await setDoc(doc(db, 'userProfiles', unlinkedCustomerUid), {
      email: 'guest@example.com',
      role: 'customer',
      name: 'Guest',
    });
    await setDoc(doc(db, 'users', consultantUid, 'customers', customerDocId), {
      firstName: 'Ayse',
      lastName: 'Yilmaz',
      linkedUserId: linkedCustomerUid,
    });
    await setDoc(doc(db, 'careerRoadmap', 'level-1'), {
      title: 'Baslangic',
      vpRequired: 0,
    });
    await setDoc(doc(db, 'recipes', 'online-shake'), {
      productId: 'formul1_id',
      title: 'Online Shake',
      description: 'Test tarifi',
      prepTimeMin: 5,
      calories: 200,
      goals: ['healthy_living'],
      tags: ['shake'],
      ingredients: [],
      steps: ['Karistir'],
      isRecommended: true,
    });
  });
}

async function runTest(name, fn) {
  try {
    await testEnv.clearFirestore();
    await seedBaseData();
    await fn();
    console.log(`ok - ${name}`);
  } catch (error) {
    console.error(`not ok - ${name}`);
    throw error;
  }
}

await runTest('consultant can create a scheduled follow-up for own customer', async () => {
  const db = authDb(consultantUid);
  await assertSucceeds(
    setDoc(doc(db, 'scheduled_follow_ups', 'allowed-create'), scheduledFollowUp()),
  );
});

await runTest('consultant cannot create a scheduled follow-up for a missing customer', async () => {
  const db = authDb(consultantUid);
  await assertFails(
    setDoc(
      doc(db, 'scheduled_follow_ups', 'missing-customer'),
      scheduledFollowUp({ customerId: 'missing-customer' }),
    ),
  );
});

await runTest('consultant can complete and snooze own scheduled follow-up', async () => {
  await testEnv.withSecurityRulesDisabled(async (context) => {
    await setDoc(
      doc(context.firestore(), 'scheduled_follow_ups', 'own-follow-up'),
      scheduledFollowUp(),
    );
  });

  const db = authDb(consultantUid);
  await assertSucceeds(
    updateDoc(doc(db, 'scheduled_follow_ups', 'own-follow-up'), {
      isCompleted: true,
    }),
  );
  await assertSucceeds(
    updateDoc(doc(db, 'scheduled_follow_ups', 'own-follow-up'), {
      dueDate: Timestamp.fromDate(new Date('2026-07-21T09:00:00Z')),
    }),
  );
});

await runTest('consultant cannot hijack identity fields on scheduled follow-up update', async () => {
  await testEnv.withSecurityRulesDisabled(async (context) => {
    await setDoc(
      doc(context.firestore(), 'scheduled_follow_ups', 'locked-fields'),
      scheduledFollowUp(),
    );
  });

  const db = authDb(consultantUid);
  await assertFails(
    updateDoc(doc(db, 'scheduled_follow_ups', 'locked-fields'), {
      consultantId: otherConsultantUid,
    }),
  );
  await assertFails(
    updateDoc(doc(db, 'scheduled_follow_ups', 'locked-fields'), {
      isAutoGenerated: true,
    }),
  );
});

await runTest('other consultant cannot read, update, or delete another consultant follow-up', async () => {
  await testEnv.withSecurityRulesDisabled(async (context) => {
    await setDoc(
      doc(context.firestore(), 'scheduled_follow_ups', 'private-follow-up'),
      scheduledFollowUp(),
    );
  });

  const db = authDb(otherConsultantUid);
  await assertFails(getDoc(doc(db, 'scheduled_follow_ups', 'private-follow-up')));
  await assertFails(
    updateDoc(doc(db, 'scheduled_follow_ups', 'private-follow-up'), {
      isCompleted: true,
    }),
  );
  await assertFails(deleteDoc(doc(db, 'scheduled_follow_ups', 'private-follow-up')));
});

await runTest('linked customer can read but cannot write scheduled follow-up', async () => {
  await testEnv.withSecurityRulesDisabled(async (context) => {
    await setDoc(
      doc(context.firestore(), 'scheduled_follow_ups', 'linked-customer-read'),
      scheduledFollowUp(),
    );
  });

  const db = authDb(linkedCustomerUid);
  const snapshot = await assertSucceeds(
    getDoc(doc(db, 'scheduled_follow_ups', 'linked-customer-read')),
  );
  assert.equal(snapshot.exists(), true);
  await assertFails(
    updateDoc(doc(db, 'scheduled_follow_ups', 'linked-customer-read'), {
      isCompleted: true,
    }),
  );
});

await runTest('careerRoadmap is signed-in read only', async () => {
  await assertFails(getDoc(doc(unauthDb(), 'careerRoadmap', 'level-1')));
  await assertSucceeds(getDoc(doc(authDb(consultantUid), 'careerRoadmap', 'level-1')));
  await assertFails(
    setDoc(doc(authDb(consultantUid), 'careerRoadmap', 'level-2'), {
      title: 'Malicious',
      vpRequired: 1,
    }),
  );
});

await runTest('recipes are signed-in read only', async () => {
  await assertFails(getDoc(doc(unauthDb(), 'recipes', 'online-shake')));
  const snapshot = await assertSucceeds(
    getDocs(collection(authDb(linkedCustomerUid), 'recipes')),
  );
  assert.equal(snapshot.size, 1);
  await assertFails(
    setDoc(doc(authDb(consultantUid), 'recipes', 'client-write'), {
      title: 'Unauthorized recipe',
    }),
  );
  await assertFails(
    updateDoc(doc(authDb(consultantUid), 'recipes', 'online-shake'), {
      title: 'Changed',
    }),
  );
  await assertFails(
    deleteDoc(doc(authDb(consultantUid), 'recipes', 'online-shake')),
  );
});

await runTest('only distributors can create a valid recipe', async () => {
  await assertSucceeds(
    setDoc(doc(authDb(consultantUid), 'recipes', 'distributor-created'), recipeDocument()),
  );
  await assertFails(
    setDoc(doc(authDb(linkedCustomerUid), 'recipes', 'customer-created'), recipeDocument()),
  );
  await assertFails(
    setDoc(
      doc(authDb(consultantUid), 'recipes', 'invalid-recipe'),
      recipeDocument({ calories: -1 }),
    ),
  );
  await assertFails(
    updateDoc(doc(authDb(consultantUid), 'recipes', 'online-shake'), {
      title: 'Değiştirilemez',
    }),
  );
});

await runTest('assigned consultant can disconnect linked customer profile', async () => {
  await assertSucceeds(
    updateDoc(doc(authDb(consultantUid), 'userProfiles', linkedCustomerUid), {
      assignedDistributorId: deleteField(),
    }),
  );
  await assertFails(
    updateDoc(doc(authDb(otherConsultantUid), 'userProfiles', linkedCustomerUid), {
      assignedDistributorId: deleteField(),
    }),
  );
});

await runTest('linked customer can create a pending order only for an active assigned coach', async () => {
  await assertSucceeds(
    setDoc(
      doc(authDb(linkedCustomerUid), 'users', consultantUid, 'orders', 'customer-order'),
      orderDocument(),
    ),
  );
});

await runTest('unlinked guest cannot create an order in their own area', async () => {
  await assertFails(
    setDoc(
      doc(authDb(unlinkedCustomerUid), 'users', unlinkedCustomerUid, 'orders', 'orphan-order'),
      orderDocument({
        userId: unlinkedCustomerUid,
        customerId: unlinkedCustomerUid,
        customerName: 'Guest',
      }),
    ),
  );
});

await runTest('customer cannot send an order to a missing coach profile', async () => {
  await testEnv.withSecurityRulesDisabled(async (context) => {
    await setDoc(doc(context.firestore(), 'userProfiles', linkedCustomerUid), {
      email: 'customer@example.com',
      role: 'customer',
      name: 'Customer',
      assignedDistributorId: 'missing-coach',
    });
  });

  await assertFails(
    setDoc(
      doc(authDb(linkedCustomerUid), 'users', 'missing-coach', 'orders', 'stale-coach-order'),
      orderDocument({ userId: 'missing-coach' }),
    ),
  );
});

await testEnv.cleanup();
