import 'package:cloud_firestore/cloud_firestore.dart';

/// Gelecekte yapılması planlanmış bir takip görevini temsil eden veri modeli.
class ScheduledFollowUpModel {
  /// Firestore'daki dokümanın benzersiz kimliği (ID).
  final String id;

  /// Bu görevin hangi danışmana atandığını belirtir.
  /// Ana sayfadaki "ajandam" sorgusu için bu alana ihtiyacımız var.
  final String consultantId;

  /// Bu görevin hangi müşteriye ait olduğunu belirtir.
  final String customerId;

  /// Müşterinin adı. Ana sayfada müşteri bilgilerini tekrar çekmemek için
  /// burada "denormalize" ederek (kopyasını tutarak) saklıyoruz. Bu, performansı artırır.
  final String customerFirstName;

  /// Müşterinin soyadı. Tıpkı adı gibi, performansı artırmak için burada saklanır.
  final String customerLastName;

  /// Bu takip görevinin yapılması gereken son tarih.
  final Timestamp dueDate;

  /// Görevin başlığı. Örneğin: "3. Gün Kontrolü".
  final String title;

  /// Bu görevin tamamlanıp tamamlanmadığını belirten bayrak.
  /// Kullanıcı takip görüşmesi eklediğinde bu `true` olarak güncellenir.
  bool isCompleted;

  /// Takip hakkında opsiyonel notlar.
  final String? notes;

  /// Takibin oluşturulma tarihi.
  final Timestamp? createdAt;

  /// Sipariş tesliminde otomatik olarak mı oluşturulduğunu belirtir.
  /// `true` ise sistem tarafından otomatik oluşturulmuştur,
  /// `false` ise danışman tarafından manuel olarak eklenmiştir.
  final bool isAutoGenerated;

  ScheduledFollowUpModel({
    required this.id,
    required this.consultantId,
    required this.customerId,
    required this.customerFirstName,
    required this.customerLastName,
    required this.dueDate,
    required this.title,
    this.isCompleted = false,
    this.notes,
    this.createdAt,
    this.isAutoGenerated = false,
  });

  /// Müşterinin tam adını döndüren yardımcı getter.
  String get customerFullName =>
      '$customerFirstName $customerLastName'.trim();

  /// Firestore'dan gelen Map verisini ScheduledFollowUpModel nesnesine dönüştürür.
  factory ScheduledFollowUpModel.fromMap(
    Map<String, dynamic> map,
    String documentId,
  ) {
    return ScheduledFollowUpModel(
      id: documentId,
      consultantId: map['consultantId'] ?? '',
      customerId: map['customerId'] ?? '',
      customerFirstName: map['customerFirstName'] ?? '',
      customerLastName: map['customerLastName'] ?? '',
      dueDate: map['dueDate'] as Timestamp? ?? Timestamp.now(),
      title: map['title'] ?? 'Planlanmış Görev',
      isCompleted: map['isCompleted'] ?? false,
      notes: map['notes'] as String?,
      createdAt: map['createdAt'] as Timestamp?,
      isAutoGenerated: map['isAutoGenerated'] ?? false,
    );
  }

  /// ScheduledFollowUpModel nesnesini Firestore'a yazmak için Map'e dönüştürür.
  Map<String, dynamic> toMap() {
    return {
      'consultantId': consultantId,
      'customerId': customerId,
      'customerFirstName': customerFirstName,
      'customerLastName': customerLastName,
      'dueDate': dueDate,
      'title': title,
      'isCompleted': isCompleted,
      'notes': notes,
      'createdAt': createdAt ?? FieldValue.serverTimestamp(),
      'isAutoGenerated': isAutoGenerated,
    };
  }

  /// Mevcut nesnenin bir kopyasını oluşturur ve belirtilen alanları günceller.
  ScheduledFollowUpModel copyWith({
    String? id,
    String? consultantId,
    String? customerId,
    String? customerFirstName,
    String? customerLastName,
    Timestamp? dueDate,
    String? title,
    bool? isCompleted,
    String? notes,
    Timestamp? createdAt,
    bool? isAutoGenerated,
  }) {
    return ScheduledFollowUpModel(
      id: id ?? this.id,
      consultantId: consultantId ?? this.consultantId,
      customerId: customerId ?? this.customerId,
      customerFirstName: customerFirstName ?? this.customerFirstName,
      customerLastName: customerLastName ?? this.customerLastName,
      dueDate: dueDate ?? this.dueDate,
      title: title ?? this.title,
      isCompleted: isCompleted ?? this.isCompleted,
      notes: notes ?? this.notes,
      createdAt: createdAt ?? this.createdAt,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    );
  }
}
