// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkFHfACTB0Hozt8mwpspZ068GOMaH7BbY',
    appId: '1:433193562880:web:db4819985d4e39da50b9e5',
    messagingSenderId: '433193562880',
    projectId: 'herbaformix',
    authDomain: 'herbaformix.firebaseapp.com',
    storageBucket: 'herbaformix.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk2OIBziqCzQd3gQKiXbNGLzeKFHHE9vQ',
    appId: '1:433193562880:android:ecf17521acef5d7c50b9e5',
    messagingSenderId: '433193562880',
    projectId: 'herbaformix',
    storageBucket: 'herbaformix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMFk7vRBZO5oLINQrZxd_yPgNDvOXf-sU',
    appId: '1:433193562880:ios:e7e5cbe7fc2d6cfc50b9e5',
    messagingSenderId: '433193562880',
    projectId: 'herbaformix',
    storageBucket: 'herbaformix.firebasestorage.app',
    iosBundleId: 'com.mze.herbaformix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNWikNbJucqFVYfk76wXJSxqjYZtzvjGk',
    appId: '1:433193562880:web:67a43de2d97f8c3350b9e5',
    messagingSenderId: '433193562880',
    projectId: 'herbaformix',
    authDomain: 'herbaformix.firebaseapp.com',
    storageBucket: 'herbaformix.firebasestorage.app',
  );
}
